# -*- coding: utf-8 -*-
"""Statistics_Practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-_rLQ6MXXJksRGs_JD_S7sMSg-YQE6V3
"""

import scipy.stats as stats
import numpy as np
data = [4,5,6,6,6,7,8,12,13,13,14,18]

zscores = stats.zscore(data)
print(zscores)

find_std = np.std(data)
print('std is:', find_std)

find_mean = np.mean(data)
print('mean values:',find_mean)

find_mode = stats.mode(data)
print('mode value:', find_mode)

import numpy as np
data = [4,25,6,15,12,13,45,14,18,25,26,31,10,55,34,8,40]
print(np.histogram(data, bins='auto'))

import matplotlib.pyplot as plt
import numpy as np
data = [4,25,6,15,12,13,45,14,18,25,26,31,10,55,34,8,40]
plt.hist(data, bins='auto')
plt.title('Histogram_Sample')
plt.show()